version: "3"

services:
  bot:
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app:cached
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    image: "redis:alpine"
